//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdicionarVeiculo
    {
        private string v1;
        private string v2;
        private int v3;

        public AdicionarVeiculo(string v1, string v2, int v3) {
            this.v1 = v1;
            this.v2 = v2;
            this.v3 = v3;
        }

        public string Placa { get; set; }
        public string Modelo { get; set; }
        public int Kml { get; set; }
    }
}
